### ISSUE TITLE
question

### ISSUE THREAD

**Issue by maartenkr** [pdwonline/youless#1]
I really have a noob question what is the main folder?
the first line in the text

create a folder called 'custom_components' into your Home Assistant folder
I've tried it in different places but I can't get it working

**Comment by pdwonline** [comment]
The main folder is the folder that HomeAssistant is installed to. it contains usually your configuration.yaml file. See screenshot of my installation..

![afbeelding](https://user-images.githubusercontent.com/6775870/58435680-e5906600-80c1-11e9-8d9a-93ff2331f0c6.png)

**Comment by maartenkr** [comment]
My folder lool like this
![fout](https://user-images.githubusercontent.com/51090293/58436222-8122d600-80c4-11e9-842e-4cf276a9dce0.jpg)

**Comment by pdwonline** [comment]
That's the config level. Go one folder up and add the custom_components folder there

**Comment by maartenkr** [comment]
I make the folder there. I wil give my log file this afternoon
